name: Deploy

on:
    push:
      branches:
        - main

jobs:
  Install:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install


  build:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dprakash0321/ttd_latest_updates:latest
