name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Readme.md' # Ignore pushes where only README.md is changed
#  schedule:
 #   - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  Install:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dprakash0321/ttd_latest_updates:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

     
  log_date_and_time:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update last deploy time
        run: |
          echo "Last deploy (IST): $(TZ=Asia/Kolkata date)" >> last_deploy.txt || echo "Last deploy (IST): $(TZ=Asia/Kolkata date)" > last_deploy.txt
        if: always()

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.USERNAME}}
          git config --global user.email ${{ secrets.USER_EMAIL}}

      - name: Commit and push changes
        run: |
          git pull origin main --rebase=false
          git add last_deploy.txt
          git commit -m "Update last deploy time [skip ci]"
          git push origin main

