name: Update README with TTD Latest Update

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest updates from TTD API
        id: fetch-updates
        run: |
          response=$(curl -s https://ttd-latest-updates-latest.onrender.com/latest-updates)
          echo "$response" > new_response.json

      - name: Convert JSON to HTML Table
        id: convert-to-table
        run: |
          updates=$(jq -r '
            def to_html:
              "<table><thead><tr><th>ID</th><th>Tag</th><th>Data</th><th>Published At</th></tr></thead><tbody>" +
              (map("<tr><td>" + (.id | tostring) + "</td><td>" + (.tag // "N/A") + "</td><td>" + .data + "</td><td>" + .publishedAt + "</td></tr>") | join("")) +
              "</tbody></table>";
            to_html' new_response.json)

          echo "$updates" > updates_table.html

      - name: Update Readme.md
        id: update-readme
        run: |
          new_updates=$(cat updates_table.html)

          # Modify Readme.md to update "Latest Updates" section
          awk '
            /## Latest Updates/ {f=1} 
            f && /<\/table>/ {print "            "; f=0} 
            !f {print}
            END {if (f) print "            "; print "'"$new_updates"'"}' Readme.md > Readme.md.tmp

          mv Readme.md.tmp Readme.md

          # Save the new response as the current response for next comparison
          mv new_response.json response.json

          # Configure Git
          git config --global user.name '${{ secrets.USERNAME }}'
          git config --global user.email '${{ secrets.USER_EMAIL }}'

          # Commit and push changes if there are updates
          if [[ $(git status --porcelain) ]]; then
            git add Readme.md response.json
            git commit -m 'Update TTD Latest Updates in README'
            git push
          else
            echo "No changes to commit."
          fi

      - name: Check if README was updated
        run: |
          if [ "$(git status --porcelain)" != "" ]; then
            echo "Readme.md updated successfully."
          else
            echo "No changes to Readme.md."
          fi
