name: Update README with TTD Latest Updates

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest updates from TTD API
        id: fetch-updates
        run: |
          curl -s https://ttd-latest-updates-latest.onrender.com/latest-updates > new_response.json

      - name: Compare current and new responses
        id: compare-responses
        run: |
          diff=$(diff -q response.json new_response.json || echo "different")
          if [[ $diff == "different" ]]; then
            echo "New updates found. Updating README.md."
          else
            echo "No new updates. Exiting."
            exit 0
          fi

      - name: Convert JSON to HTML Table
        id: convert-to-table
        run: |
          updates=$(jq -r '
            def to_html:
              "<table><thead><tr><th>ID</th><th>Tag</th><th>Data</th><th>Published At</th></tr></thead><tbody>" +
              (map("<tr><td>" + (.id | tostring) + "</td><td>" + .tag + "</td><td>" + .data + "</td><td>" + .publishedAt + "</td></tr>") | join("")) +
              "</tbody></table>";
            to_html' new_response.json)

          echo "$updates" > updates_table.html

      - name: Update Readme.md
        id: update-readme
        run: |
          new_updates=$(cat updates_table.html)

          # Replace the entire "Latest Updates" section in README.md
          awk '/## Latest Updates/{p=1} p && /<!-- The content here will be replaced by the GitHub Action -->/{p=0} !p' Readme.md > Readme.md.tmp
          echo "## Latest Updates" >> Readme.md.tmp
          echo "$new_updates" >> Readme.md.tmp
          mv Readme.md.tmp Readme.md

          # Save the new response as the current response for next comparison
          mv new_response.json response.json

          # Commit and push changes
          git config --global user.name '${{ secrets.USERNAME }}'
          git config --global user.email '${{ secrets.USER_EMAIL }}'
          git add Readme.md response.json
          git commit -m 'Update TTD Latest Updates in README'
          git push

      - name: Check if README was updated
        run: |
          if [ "$(git status --porcelain)" != "" ]; then
            echo "Readme.md updated successfully."
          else
            echo "No changes to Readme.md."
          fi
