name: Update README with TTD Latest Updates

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest updates from TTD API
        id: fetch-updates
        run: |
          response=$(curl -s https://ttd-latest-updates-latest.onrender.com/latest-updates)
          echo "$response" > new_response.json

      - name: Convert JSON to HTML Table
        id: convert-to-table
        run: |
          updates=$(jq -r '
            def to_html:
              "<table><thead><tr><th>ID</th><th>Tag</th><th>Data</th><th>Published At</th></tr></thead><tbody>" +
              (map("<tr><td>" + (.id | tostring) + "</td><td>" + (.tag // "N/A") + "</td><td>" + .data + "</td><td>" + .publishedAt + "</td></tr>") | join("")) +
              "</tbody></table>";
            to_html' new_response.json)

          echo "$updates" > updates_table.html

      - name: Update Readme.md
        id: update-readme
        run: |
          new_updates=$(cat updates_table.html)

          # Remove existing "Latest Updates" section
          sed -i '/## Latest Updates/,/<!-- The content here will be replaced by the GitHub Action -->/d' Readme.md

          # Add new "Latest Updates" section with updated content
          echo "## Latest Updates" >> Readme.md
          echo "$new_updates" >> Readme.md

          # Save the new response as the current response for next comparison
          mv new_response.json response.json

      - name: Check if README needs updating
        id: check-readme
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=needs_update::true"
          else
            echo "::set-output name=needs_update::false"
          fi

      - name: Commit and push changes
        if: steps.check-readme.outputs.needs_update == 'true'
        run: |
          git config --global user.name '${{ secrets.USERNAME }}'
          git config --global user.email '${{ secrets.USER_EMAIL }}'
          git add Readme.md response.json
          git commit -m 'Update TTD Latest Updates in README'
          git push

      - name: Check if README was updated
        run: |
          if [ "${{ steps.check-readme.outputs.needs_update }}" == 'true' ]; then
            echo "Readme.md updated successfully."
          else
            echo "No changes to Readme.md."
          fi
