name: Update README with TTD Latest Updates

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest updates from TTD API
        id: fetch-updates
        run: |
          response=$(curl -s https://ttd-latest-updates-latest.onrender.com/latest-updates)
          echo "$response" > response.json

      - name: Convert JSON to Markdown Table
        id: convert-to-table
        run: |
          updates=$(jq -r '
            [
              "ID", "Tag", "Data", "Published At"
            ],
            (.[] | [
              .id, 
              (.tag // "N/A"), 
              (.data | gsub("\n"; " ") | gsub("  "; " ")), 
              .publishedAt
            ]) 
            | @csv' response.json | sed 's/^/| /;s/","/ | /g;s/"$//;s/^"//;s/"/\|/g')

          table=$(echo "$updates" | sed 's/"/|/g' | sed '1s/^/| /;1s/$/ |/;1a|---|---|---|---|')

          echo "$table" > updates_table.md

      - name: Update Readme.md
        id: update-readme
        run: |
          new_updates=$(cat updates_table.md)

          # Extract the content before "## Latest Updates"
          before_updates=$(sed -n '1,/## Latest Updates/p' Readme.md)

          # Extract the content after the table
          after_updates=$(sed -n '/## Latest Updates/,$p' Readme.md | sed '1,/|---|---|---|---|/d')

          # Combine the new updates into the README
          echo "$before_updates" > Readme.md
          echo "$new_updates" >> Readme.md
          echo "$after_updates" >> Readme.md

          # Commit and push changes
          git config --global user.name ${{ secrets.USERNAME}}
          git config --global user.email ${{ secrets.USER_EMAIL}}
          git add Readme.md
          git commit -m 'Update TTD Latest Updates in README'
          git push

      - name: Check if README was updated
        run: |
          if [ "$(git status --porcelain)" != "" ]; then
            echo "Readme.md updated successfully."
          else
            echo "No changes to Readme.md."
          fi
